version: '3.9'

services:
  backend:
    build:
      context: ./back
    command: gunicorn --bind 0.0.0.0:8000 prjct.wsgi --workers=4
    expose:
      - 8000
  frontend:
    build: 
      context: ./front
    volumes:
      - react_build:/react/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend
volumes:
  react_build: